//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitoshka
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupParticipant
    {
        public int ID { get; set; }
        public Nullable<int> IDPedagog { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public Nullable<int> IDEvents { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Group Group { get; set; }
        public virtual Users Users { get; set; }
    }
}
