//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitoshka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListGroups
    {
        public int ID { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public Nullable<int> IDChild { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Group Group { get; set; }
    }
}
